// tomltestgen retrieves a given version of the language-agnostic TOML test suite in
// https://github.com/BurntSushi/toml-test and generates go-toml unit tests.
//
// Within the go-toml package, run `go generate`.  Otherwise, use:
//
//	go run ./cmd/tomltestgen -o toml_testgen_test.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
	"unicode"

	"github.com/pelletier/go-toml/v2/unstable"
)

type testCase struct {
	Name    string
	Input   string
	JSONRef string
}

var (
	ref      = flag.String("r", "master", "git reference")
	out      = flag.String("o", "", "output file")
	pkg      = flag.String("p", "toml_test", "package name")
	jsonFlag = flag.Bool("json", false, "emit JSON reference table (valid only)")
	astFlag  = flag.Bool("ast", false, "emit AST builder table (valid only)")
)

func usage() {
	_, _ = fmt.Fprintf(os.Stderr, "usage: tomltestgen [flags]\n")
	flag.PrintDefaults()
}

func kebabToCamel(kebab string) string {
	var buf strings.Builder
	nextUpper := true
	for _, c := range kebab {
		if nextUpper {
			buf.WriteRune(unicode.ToUpper(c))
			nextUpper = false
		} else {
			switch c {
			case '-':
				nextUpper = true
			case '/':
				nextUpper = true
				buf.WriteByte('_')
			default:
				buf.WriteRune(c)
			}
		}
	}
	return buf.String()
}

func collectCases() (invalidCases, validCases []testCase) {
	dirContent, _ := filepath.Glob("tests/invalid/**/*.toml")
	for _, f := range dirContent {
		filename := strings.TrimPrefix(f, "tests/valid/")
		name := kebabToCamel(strings.TrimSuffix(filename, ".toml"))
		name = strings.ReplaceAll(name, ".", "_")

		log.Printf("> [%s] %s\n", "invalid", name)

		tomlContent, err := os.ReadFile(f) // #nosec G304
		if err != nil {
			fmt.Printf("failed to read test file: %s\n", err)
			os.Exit(1)
		}

		invalidCases = append(invalidCases, testCase{
			Name:  name,
			Input: string(tomlContent),
		})
	}

	dirContent, _ = filepath.Glob("tests/valid/**/*.toml")
	for _, f := range dirContent {
		filename := strings.TrimPrefix(f, "tests/valid/")
		name := kebabToCamel(strings.TrimSuffix(filename, ".toml"))
		name = strings.ReplaceAll(name, ".", "_")

		log.Printf("> [%s] %s\n", "valid", name)

		tomlContent, err := os.ReadFile(f) // #nosec G304
		if err != nil {
			fmt.Printf("failed reading test file: %s\n", err)
			os.Exit(1)
		}

		jsonFile := strings.TrimSuffix(f, ".toml") + ".json"
		jsonContent, err := os.ReadFile(jsonFile) // #nosec G304
		if err != nil {
			fmt.Printf("failed reading validation json: %s\n", err)
			os.Exit(1)
		}

		validCases = append(validCases, testCase{
			Name:    name,
			Input:   string(tomlContent),
			JSONRef: string(jsonContent),
		})
	}

	log.Printf("Collected %d tests from toml-test\n", len(invalidCases)+len(validCases))
	return
}

func header() string {
	return fmt.Sprintf("// Code generated by tomltestgen for toml-test ref %s on %s. DO NOT EDIT.\npackage %s\n\n", *ref, time.Now().Format(time.RFC3339), *pkg)
}

func generateDefault(invalidCases, validCases []testCase) []byte {
	var buf bytes.Buffer
	buf.WriteString(header())

	buf.WriteString("var testgenInvalidCases = map[string]string{\n")
	for _, c := range invalidCases {
		fmt.Fprintf(&buf, "\t%s: %s,\n", strconv.Quote(c.Name), strconv.Quote(c.Input))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("var testgenValidCases = map[string]string{\n")
	for _, c := range validCases {
		fmt.Fprintf(&buf, "\t%s: %s,\n", strconv.Quote(c.Name), strconv.Quote(c.Input))
	}
	buf.WriteString("}\n")

	return buf.Bytes()
}

func generateJSON(validCases []testCase) []byte {
	var buf bytes.Buffer
	buf.WriteString(header())

	buf.WriteString("var testgenValidJSONRef = map[string]string{\n")
	for _, c := range validCases {
		fmt.Fprintf(&buf, "\t%s: %s,\n", strconv.Quote(c.Name), strconv.Quote(c.JSONRef))
	}
	buf.WriteString("}\n")

	return buf.Bytes()
}

func generateAST(validCases []testCase) []byte {
	qual := "unstable."
	if *pkg == "unstable" {
		qual = ""
	}

	var buf bytes.Buffer
	buf.WriteString(header())

	if qual != "" {
		buf.WriteString("import \"github.com/pelletier/go-toml/v2/unstable\"\n\n")
	}

	// tree helper function
	fmt.Fprintf(&buf, "func tree(b *%sBuilder, n %sNode, children ...%sReference) %sReference {\n", qual, qual, qual, qual)
	buf.WriteString("\tref := b.Push(n)\n")
	fmt.Fprintf(&buf, "\tvar prev %sReference\n", qual)
	buf.WriteString("\tfor i, child := range children {\n")
	buf.WriteString("\t\tif i == 0 {\n")
	buf.WriteString("\t\t\tb.AttachChild(ref, child)\n")
	buf.WriteString("\t\t} else {\n")
	buf.WriteString("\t\t\tb.Chain(prev, child)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tprev = child\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn ref\n")
	buf.WriteString("}\n\n")

	// AST cases map
	fmt.Fprintf(&buf, "var testgenASTCases = map[string]func(b *%sBuilder) []%sReference{\n", qual, qual)

	var p unstable.Parser
	for _, c := range validCases {
		p.Reset([]byte(c.Input))

		var exprs []string
		for p.NextExpression() {
			expr := p.Expression()
			var exprBuf strings.Builder
			emitTreeCall(expr, 3, qual, &exprBuf)
			exprs = append(exprs, exprBuf.String())
		}
		if err := p.Error(); err != nil {
			log.Fatalf("failed to parse %s: %s", c.Name, err)
		}

		fmt.Fprintf(&buf, "\t%s: func(b *%sBuilder) []%sReference {\n", strconv.Quote(c.Name), qual, qual)
		fmt.Fprintf(&buf, "\t\treturn []%sReference{\n", qual)
		for _, e := range exprs {
			buf.WriteString(e)
			buf.WriteString(",\n")
		}
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t},\n")
	}

	buf.WriteString("}\n")

	return buf.Bytes()
}

func emitTreeCall(node *unstable.Node, indent int, qual string, buf *strings.Builder) {
	prefix := strings.Repeat("\t", indent)

	buf.WriteString(prefix)
	buf.WriteString("tree(b, ")
	buf.WriteString(qual)
	buf.WriteString("Node{Kind: ")
	buf.WriteString(qual)
	buf.WriteString(node.Kind.String())

	if len(node.Data) > 0 {
		buf.WriteString(", Data: []byte(")
		buf.WriteString(strconv.Quote(string(node.Data)))
		buf.WriteString(")")
	}
	buf.WriteString("}")

	// Collect children
	var children []*unstable.Node
	it := node.Children()
	for it.Next() {
		children = append(children, it.Node())
	}

	if len(children) == 0 {
		buf.WriteString(")")
		return
	}

	for _, child := range children {
		buf.WriteString(",\n")
		emitTreeCall(child, indent+1, qual, buf)
	}
	buf.WriteString(",\n")
	buf.WriteString(prefix)
	buf.WriteString(")")
}

func formatSource(src []byte) []byte {
	formatted, err := format.Source(src)
	if err != nil {
		for i, line := range strings.Split(string(src), "\n") {
			log.Printf("%4d: %s", i+1, line)
		}
		log.Fatalf("failed to format source: %s", err)
	}
	return formatted
}

func writeOutput(data []byte) {
	if *out == "" {
		fmt.Print(string(data))
		return
	}
	err := os.WriteFile(*out, data, 0o600)
	if err != nil {
		log.Fatalf("failed to write output: %s", err)
	}
}

func main() {
	flag.Usage = usage
	flag.Parse()

	invalidCases, validCases := collectCases()

	var raw []byte
	switch {
	case *jsonFlag:
		raw = generateJSON(validCases)
	case *astFlag:
		raw = generateAST(validCases)
	default:
		raw = generateDefault(invalidCases, validCases)
	}

	writeOutput(formatSource(raw))
}
